### ISSUE TITLE
Comprommised wallet with honeypot

### ISSUE THREAD

**Issue by abadon666** [whonion/ts-zkpepe-claimer#1]
hi dev...can you to do a modification...for move tokens out from comprommised wallet after claim...??
i mean...to do 
1) to do claim
2)move tokens to safe wallet
thanks

**Comment by whonion** [comment]
Hey there!
1. At the moment, the claim has not been fully realized yet.(project in progress).
2. To save claimed-tokens for a compromised private key we need to use a slightly different approach (flashbots). You can explore the following repositories if you have a similar problem:
 - https://github.com/whonion/ens-claim-flashbot-example
 - https://github.com/codeesura/ethereum-safe-token-transfer-flashbots
3. I can add a module to send all claimed tokens to one address in a batch transaction, but this does not guarantee that they'll not be draine if your private key is compromised, since there is no function in the token distributor's contract to specify another recipient (**claim by signature**, for example)

**Comment by abadon666** [comment]
hi dev...thanks for your reply
if you can add a module to send all claimed tokens to one address in a batch transaction...in the next days when the claim is fully realized...maybe there will be function in the token distributor's contract to specify another recipient ..thanks for your help

1 another problem is pay fees for the gas by 1 my safe address ( sponsor address i mean)...

**Comment by whonion** [comment]
Hey there!
I'm sorry, but the claim to another address feature will not appear, as the distributor's token  contract  is already deployed in the zkSync network.
<img width="707" alt="image" src="https://github.com/whonion/ts-zkpepe-claimer/assets/47848969/dd4a2c95-17e1-4ca3-a274-ddf26384a0b6">
As for paying commission with **sponsor address**, that should only be done via flashbots, but I'm not quite sure if that can be done in zkSync yet

**Comment by abadon666** [comment]
hi dev...in github i have try 
https://github.com/SZharkov/arbitrum-airdrop-claimer
This script was created in order to claim an Arbitrum airdrop instantly when distribution starts. After claiming script can transfer tokens to any address. It also supports multiple accounts, so you can even claim on 50+ accounts and still send tokens to different addresses
this was for arbitrum airdrop...is it possible to do a modify for zkpepe airdrop....thanks

**Comment by whonion** [comment]
Claiming $ARB tokens used the Claim function without parameters.
Yes it is possible to send tokens to another address. But your case, when the private key is compromised and you need to send the tokens before they are drained, is a bit different
